import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'sjm' at '8/3/15 12:18 AM' with Gradle 2.5
 *
 * @author sjm, @date 8/3/15 12:18 AM
 */
public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        //Library classUnderTest = new Library();
        //assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
